name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show perl version
        run: perl -v
      - name: Install Perl::Critic
        run: sudo cpanm --notest Perl::Critic
      - name: make check
        run: make check
